//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NajlotSnippetStudio.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NajlotSnippetStudio.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon App {
            get {
                object obj = ResourceManager.GetObject("App", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.IO;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Windows.Forms;
        ///using System.Threading.Tasks;
        ///using System.Collections.Generic;
        ///
        ///public class MainClass
        ///{
        ///	/// &lt;summary&gt;
        ///	/// Template text defined above
        ///	/// &lt;/summary&gt;
        ///	public string Template { get; set; }
        ///
        ///	/// &lt;summary&gt;
        ///	/// Dictionary with variables filled by user
        ///	/// &lt;/summary&gt;
        ///	public Dictionary&lt;string, string&gt; Variables { get; set; }
        ///
        ///	/// &lt;summary&gt;
        ///	/// Text taken from clipboard
        ///	/// &lt;/summary&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InitialCodeCS {
            get {
                return ResourceManager.GetString("InitialCodeCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imports System
        ///Imports System.IO
        ///Imports System.Linq
        ///Imports System.Text
        ///Imports System.Windows.Forms
        ///Imports System.Threading.Tasks
        ///Imports System.Collections.Generic
        ///
        ///Public Class MainClass
        ///	&apos;&apos;&apos; &lt;summary&gt;
        ///	&apos;&apos;&apos; Template text defined above
        ///	&apos;&apos;&apos; &lt;/summary&gt;
        ///	Property Template As String
        ///
        ///	&apos;&apos;&apos; &lt;summary&gt;
        ///	&apos;&apos;&apos; Dictionary with variables filled by user
        ///	&apos;&apos;&apos; &lt;/summary&gt;
        ///	Property Variables As Dictionary(Of String, String)
        ///	&apos;&apos;&apos; &lt;summary&gt;
        ///	&apos;&apos;&apos; Text taken from clipboard
        ///	&apos;&apos;&apos; &lt;/summary&gt;
        ///	Public Prope [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InitialCodeVB {
            get {
                return ResourceManager.GetString("InitialCodeVB", resourceCulture);
            }
        }
    }
}
